// <auto-generated />
namespace Sibers_test_task.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StartMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202212011506412_StartMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
